Dev message and ip limit
85yago/go_small_chat pull request #28
Opened 2022-12-11 13:10 UTC by iorar

文字数制限と海外IP制限を追加する。

2022-12-11 15:52 UTC, iorar commented
This closes #27

2022-12-11 17:42 UTC, 85yago requested changes
最大長はみ出てもそのまま書き込むか、書き込まずエラーを返すかどうかを仕様に書き足した方が良さそう。
それだけやったらマージしてもいいと思う。

2022-12-11 17:42 UTC, 85yago commented on app/post_message.go
> +		if utf8.RuneCountInString(writedata.Message) > MSG_MAX_LEN {
最大長を超えてても書き込みはするのね

2022-12-11 17:42 UTC, 85yago commented on app/ipban_mw.go
> +			ctx.JSON(418, "I'm a teapot")
草

2022-12-12 10:06 UTC, iorar commented on app/post_message.go
> +		if utf8.RuneCountInString(writedata.Message) > MSG_MAX_LEN {
書き込みますね

2022-12-12 14:13 UTC, 85yago approved these changes
よさ

2022-12-12 14:13 UTC, merged